; Custom NSIS installer script for Linux AI Ops Studio
; Extends the default electron-builder generated installer

!include "MUI2.nsh"
!include "x64.nsh"

; Get the installer script generated by electron-builder
!include "${BUILD_RESOURCES_DIR}/nsis/installer.nsh"

; Add a custom page after installation to prompt for API key
; This is called after the main install finishes
Function .onInstSuccess
  ; Ask if user wants to configure AI API key
  MessageBox MB_YESNO "¿Deseas configurar una clave API de OpenRouter para habilitar la IA?$\n$\nPuedes hacerlo ahora o después desde la aplicación." /SD IDNO IDYES ConfigureAPI IDNO SkipAPI

  ConfigureAPI:
    ; Prompt for API key
    ${GetParameters} $0
    StrCpy $1 ""

    ; Use a simple input dialog (PowerShell would be cleaner but NSIS is more portable)
    ; For now, we'll create a .env file with a placeholder and instructions

    ; Create .env file in AppData with instructions
    SetShellVarContext current
    StrCpy $0 "$APPDATA\linux-ai-ops-studio"
    CreateDirectory "$0"

    ; Write .env with example (user can edit it later)
    FileOpen $1 "$0\.env" w
    FileWrite $1 "# Clave API de OpenRouter$\n"
    FileWrite $1 "# Obtén tu clave en: https://openrouter.ai/keys$\n"
    FileWrite $1 "# OPENROUTER_API_KEY=sk_or_...$\n"
    FileWrite $1 "$\n"
    FileWrite $1 "# (Descomenta la línea anterior y reemplaza con tu clave)$\n"
    FileClose $1

    ; Inform user
    MessageBox MB_OK "Se creó un archivo .env en: $0$\n$\nPuedes editar ese archivo para agregar tu clave API de OpenRouter.$\n$\nReinicia la aplicación después de guardar los cambios."

    ; Open the .env file for editing
    ExecShell "open" "$0\.env"

    SkipAPI:
FunctionEnd
